version: '2'

services:

  #1.系统一些环境变量的配置
  #2.端口的映射关系
  #3.文件的映射关心

  orderer.example.com:
    container_name: orderer.example.com
#    指定使用镜像的名称
    image: hyperledger/fabric-orderer:x86_64-1.0.0
#    环境变量的配置
    environment:
#     设置日志级别
      - ORDERER_GENERAL_LOGLEVEL=debug
#     服务暴露的地址
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
#     下面两个是注入创世区块
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block
#      下面两个是证书相关的配置
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
#      -differ bug
    working_dir: /home/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
#     前面的是本机的端口，端口映射
      - 7050:7050
    volumes:
      - ./config/genesis.block:/etc/hyperledger/config/genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/orderer
#        - differ bug
#        - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peerOrg1
#    networks:
#      - basic

#peer的基础设置
  peer.base:
    image: hyperledger/fabric-peer:x86_64-1.0.0
    environment:
#     peer节点可能对chaincode做一些操作
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#     日志级别
      - CORE_LOGGING_PEER=debug
#     开启开发者模式
#      - CORE_CHAINCODE_MODE=dev
#     关于链码的日志级别
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
#      msp证书
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
#      -differ bug
#      状态数据库的储存引擎，这里配置使用levelDB
      - CORE_LEDGER_STATE_STATEDATABASE=goleveldb
#      配置chaincode与peer节点使用的网络，同一个网络
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=deploy_default
    working_dir: /home/gopath/src/github.com/hyperledger/fabric
    command: peer node start
#    开启开发者模式
#    command: peer node start --peer-chaincode=true

  peer0.org0.example.com:
    extends:
      service: peer.base
    container_name: peer0.org0.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org0.example.com
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_ADDRESS=peer0.org0.example.com:7051
    ports:
#     grpc的端口
      - 7051:7051
#     事件监听的端口
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.example.com/peers/peer0.org0.example.com:/etc/hyperledger/peer
#        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
#        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
#      - couchdb
#    networks:
#      - basic

  peer1.org0.example.com:
    extends:
      service: peer.base
    container_name: peer1.org0.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org0.example.com
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_ADDRESS=peer1.org0.example.com:7051
    ports:
      #     grpc的端口
      - 17051:7051
      #     事件监听的端口
      - 17053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.example.com/peers/peer1.org0.example.com:/etc/hyperledger/peer
    #        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    #        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
  #      - couchdb
  #    networks:
  #      - basic
# peer节点客户端配置


  peer0.org1.example.com:
    extends:
      service: peer.base
    container_name: peer0.org1.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
    ports:
      #     grpc的端口
      - 27051:7051
      #     事件监听的端口
      - 27053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com:/etc/hyperledger/peer
    #        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    #        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
  #      - couchdb
  #    networks:
  #      - basic


  peer1.org1.example.com:
    extends:
      service: peer.base
    container_name: peer1.org1.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
    ports:
      #     grpc的端口
      - 37051:7051
      #     事件监听的端口
      - 37053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com:/etc/hyperledger/peer
    #        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    #        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
  #      - couchdb
  #    networks:
  #      - basic

  peer2.org1.example.com:
    extends:
      service: peer.base
    container_name: peer2.org1.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer2.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer2.org1.example.com:7051
    ports:
      #     grpc的端口
      - 47051:7051
      #     事件监听的端口
      - 47053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com:/etc/hyperledger/peer
    #        - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    #        - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer.example.com
  #      - couchdb
  #    networks:
  #      - basic

# peer节点客户端配置
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.0
    tty: true
    environment:
      - GOPATH=/home/gopath
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@org1.example.com/msp
#      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /home/gopath/src/github.com/hyperledger/fabric/
    command: /bin/bash
    volumes:
      - ./../chaincode:/home/gopath/src/github.com/chaincode
      - ./config:/etc/hyperledger/config
      - ./crypto-config/peerOrganizations/org1.example.com:/etc/hyperledger/peer

